#!/bin/bash

# Quick DNS Setup - Interactive Script

echo "🌐 ClickAnunț DNS Configuration"
echo "================================"
echo ""

# Obține IP-ul serverului
read -p "📍 Introdu IP-ul serverului VPS (ex: 123.45.67.89): " SERVER_IP

if [ -z "$SERVER_IP" ]; then
    echo "❌ IP-ul este necesar!"
    exit 1
fi

echo ""
echo "✅ IP Server: $SERVER_IP"
echo ""
echo "📋 INSTRUCȚIUNI DNS"
echo "==================="
echo ""
echo "🔹 Provider: Unde ai cumpărat domeniul clickanunt.ro?"
echo ""
echo "1. GoDaddy"
echo "2. Namecheap"
echo "3. Cloudflare"
echo "4. Romanian Provider (Rotld, etc)"
echo "5. Altul"
echo ""
read -p "Alege (1-5): " PROVIDER

clear
echo ""
echo "🌐 Setup DNS pentru www.clickanunt.ro"
echo "Server IP: $SERVER_IP"
echo "======================================"
echo ""

case $PROVIDER in
    1)
        echo "📌 GODADDY - Pașii:"
        echo "1. Mergi pe https://godaddy.com → Login"
        echo "2. My Products → Domains"
        echo "3. Click pe 'clickanunt.ro' → DNS"
        echo "4. Add → A Record:"
        echo "   Host: @"
        echo "   Points to: $SERVER_IP"
        echo "   TTL: 1 Hour"
        echo "5. Add → A Record:"
        echo "   Host: www"
        echo "   Points to: $SERVER_IP"
        echo "   TTL: 1 Hour"
        echo "6. Save"
        ;;
    2)
        echo "📌 NAMECHEAP - Pașii:"
        echo "1. Mergi pe https://namecheap.com → Login"
        echo "2. Domain List → Manage (lângă clickanunt.ro)"
        echo "3. Advanced DNS"
        echo "4. Add New Record:"
        echo "   Type: A Record"
        echo "   Host: @"
        echo "   Value: $SERVER_IP"
        echo "   TTL: Automatic"
        echo "5. Add New Record:"
        echo "   Type: A Record"
        echo "   Host: www"
        echo "   Value: $SERVER_IP"
        echo "   TTL: Automatic"
        echo "6. Save All Changes"
        ;;
    3)
        echo "📌 CLOUDFLARE - Pașii:"
        echo "1. Mergi pe https://cloudflare.com → Login"
        echo "2. Click pe 'clickanunt.ro'"
        echo "3. DNS → Add record:"
        echo "   Type: A"
        echo "   Name: @"
        echo "   IPv4 address: $SERVER_IP"
        echo "   Proxy status: Proxied (portocaliu)"
        echo "   TTL: Auto"
        echo "4. Add record:"
        echo "   Type: A"
        echo "   Name: www"
        echo "   IPv4 address: $SERVER_IP"
        echo "   Proxy status: Proxied (portocaliu)"
        echo "   TTL: Auto"
        echo "5. Save"
        echo ""
        echo "⚠️  Dacă e prima configurare:"
        echo "   - Cloudflare îți va da 2 nameservere"
        echo "   - Mergi la registrar-ul tău (unde ai cumpărat domeniul)"
        echo "   - Schimbă nameservers cu cele de la Cloudflare"
        ;;
    4)
        echo "📌 ROMANIAN PROVIDER - Pașii Generali:"
        echo "1. Login la panoul provider-ului"
        echo "2. Găsește 'Domenii' sau 'DNS Management'"
        echo "3. Click pe 'clickanunt.ro' → Gestiune DNS"
        echo "4. Adaugă înregistrare DNS:"
        echo "   Tip: A"
        echo "   Nume/Host: @"
        echo "   Valoare: $SERVER_IP"
        echo "   TTL: 3600"
        echo "5. Adaugă înregistrare DNS:"
        echo "   Tip: A"
        echo "   Nume/Host: www"
        echo "   Valoare: $SERVER_IP"
        echo "   TTL: 3600"
        echo "6. Salvează"
        ;;
    5)
        echo "📌 PROVIDER GENERIC - Pașii:"
        echo "1. Login la panoul de administrare domeniu"
        echo "2. Caută 'DNS', 'DNS Zone', sau 'DNS Records'"
        echo "3. Adaugă 2 înregistrări A:"
        echo ""
        echo "   Înregistrarea 1:"
        echo "   - Tip/Type: A"
        echo "   - Nume/Host/Name: @ (sau lasă gol)"
        echo "   - Valoare/Value/Points to: $SERVER_IP"
        echo "   - TTL: 3600 sau 1 Hour"
        echo ""
        echo "   Înregistrarea 2:"
        echo "   - Tip/Type: A"
        echo "   - Nume/Host/Name: www"
        echo "   - Valoare/Value/Points to: $SERVER_IP"
        echo "   - TTL: 3600 sau 1 Hour"
        echo ""
        echo "4. Salvează modificările"
        ;;
esac

echo ""
echo "⏰ TIMP DE AȘTEPTARE"
echo "===================="
echo "DNS propagation durează:"
echo "- Minim: 15-30 minute"
echo "- Normal: 2-4 ore"
echo "- Maxim: 24-48 ore"
echo ""
echo "🔍 VERIFICĂ DNS-UL"
echo "=================="
echo ""
echo "După ce ai configurat DNS-ul, verifică cu:"
echo ""
echo "dig clickanunt.ro"
echo "dig www.clickanunt.ro"
echo ""
echo "Sau online:"
echo "https://dnschecker.org (recomandare)"
echo "https://www.whatsmydns.net"
echo ""
echo "✅ Când DNS-ul propagă (vezi IP-ul $SERVER_IP), continuă cu:"
echo "   sudo ./setup-server.sh"
echo ""
