// ============================================
// CATEGORII SI SUBCATEGORII (OLX-style)
// ============================================

export const CATEGORIES: Record<string, string[]> = {
  "Auto, moto și ambarcațiuni": [
    "Autoturisme",
    "Autoutilitare",
    "SUV/Off-road",
    "Camioane",
    "Rulote și remorci",
    "Motociclete/Scutere",
    "ATV",
    "Piese auto",
    "Accesorii auto",
    "Service auto",
    "Ambarcațiuni",
  ],
  "Imobiliare": [
    "Apartamente de vânzare",
    "Case de vânzare",
    "Terenuri",
    "Spații comerciale",
    "Apartamente de închiriat",
    "Case de închiriat",
    "Camere de închiriat",
    "Spații comerciale de închiriat",
    "Garaje",
  ],
  "Electronice și electrocasnice": [
    "Telefoane mobile",
    "Tablete",
    "Laptopuri",
    "Computere desktop",
    "TV",
    "Audio/Video",
    "Console jocuri",
    "Camere foto/video",
    "Frigidere",
    "Mașini de spălat",
    "Aspiratoare",
    "Aparate de aer condiționat",
    "Echipamente IT",
  ],
  "Modă și frumusețe": [
    "Îmbrăcăminte femei",
    "Îmbrăcăminte bărbați",
    "Îmbrăcăminte copii",
    "Încălțăminte",
    "Accesorii",
    "Bijuterii și ceasuri",
    "Genți",
    "Produse cosmetice",
  ],
  "Casă și grădină": [
    "Mobilă",
    "Decorațiuni",
    "Iluminat",
    "Textile casă",
    "Ustensile bucătărie",
    "Unelte și scule",
    "Echipamente grădină",
    "Plante și flori",
    "Materiale construcție",
  ],
  "Sport, timp liber și artă": [
    "Biciclete",
    "Echipament sport",
    "Fitness",
    "Camping",
    "Pescuit/Vânătoare",
    "Cărți",
    "Muzică/Film",
    "Instrumente muzicale",
    "Colecții",
    "Artă",
  ],
  "Copii și bebeluși": [
    "Haine copii/bebeluși",
    "Încălțăminte copii",
    "Cărucioare",
    "Scaune auto",
    "Jucării",
    "Cărți copii",
    "Articole școlari",
    "Mobilier copii",
  ],
  "Animale de companie": [
    "Câini",
    "Pisici",
    "Păsări",
    "Pești acvariu",
    "Rozătoare",
    "Accesorii animale",
    "Hrană animale",
  ],
  "Locuri de muncă": [
    "IT/Software",
    "Vânzări/Marketing",
    "Construcții",
    "Educație",
    "Turism/Horeca",
    "Transport/Logistică",
    "Medical",
    "Alte domenii",
  ],
  "Servicii și afaceri": [
    "Servicii IT",
    "Construcții/Renovări",
    "Reparații",
    "Transport/Mutări",
    "Curățenie",
    "Evenimente",
    "Educație/Cursuri",
    "Servicii juridice",
    "Afaceri de vânzare",
  ],
  "Agricultură": [
    "Tractoare",
    "Utilaje agricole",
    "Animale de fermă",
    "Produse agricole",
    "Terenuri agricole",
  ],
  "Altele": [
    "Diverse",
    "Pierdut/Găsit",
    "Schimb",
    "Donații",
  ],
};

export const ALL_CATEGORIES = Object.keys(CATEGORIES).sort();

// ============================================
// AUTO DATA (pentru categoria Auto)
// ============================================

// Comprehensive database of car makes and their models
export const CAR_MAKES_AND_MODELS: Record<string, string[]> = {
  // Popular European Brands
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8"],
  "BMW": ["i3", "i4", "i8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "1", "2", "3", "4", "5", "6", "7", "M235i", "M440i"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "CLA", "GLA", "GLB", "GLC", "GLE", "GLS", "AMG"],
  "Volkswagen": ["Polo", "Golf", "Jetta", "Passat", "Touran", "Tiguan", "Touareg", "T-Cross", "T-Roc", "ID.3", "ID.4"],
  "Skoda": ["Citigo", "Fabia", "Octavia", "Superb", "Kodiaq", "Karoq"],
  "Seat": ["Ibiza", "Leon", "Toledo", "Tarraco", "Arona", "Ateca"],
  "Renault": ["Clio", "Megane", "Scenic", "Espace", "Laguna", "Kadjar", "Koleos"],
  "Peugeot": ["208", "308", "3008", "5008", "408", "508", "2008"],
  "Citroen": ["C1", "C3", "C4", "C5", "Berlingo", "Picasso"],
  "Fiat": ["500", "Panda", "Tipo", "500X", "Doblo"],
  "Alfa Romeo": ["Mito", "Giulietta", "Giulia", "Stelvio", "Tonale"],
  "Lancia": ["Ypsilon", "Lybra"],
  "Hyundai": ["i10", "i20", "i30", "i40", "Elantra", "Sonata", "Santa Fe", "Tucson", "Kona", "Ioniq", "Nexo"],
  "Kia": ["Picanto", "Rio", "Ceed", "Forte", "Optima", "Niro", "Sorento", "Sportage", "Telluride", "EV6"],
  "Dacia": ["Sandero", "Logan", "Dokker", "Duster"],
  "Opel": ["Corsa", "Astra", "Insignia", "Grandland X", "Crossland X", "Zafira"],
  "Chevrolet": ["Spark", "Aveo", "Cruze", "Malibu", "Equinox", "Blazer", "Traverse"],
  "Ford": ["Fiesta", "Focus", "Mondeo", "Mustang", "Fusion", "Kuga", "Edge", "F-150"],
  "Nissan": ["Micra", "Qashqai", "Juke", "Altima", "Maxima", "Rogue", "Pathfinder", "Leaf"],
  "Toyota": ["Aygo", "Corolla", "Camry", "RAV4", "Highlander", "Prius", "Land Cruiser", "Yaris", "Avensis"],
  "Honda": ["Jazz", "Civic", "Accord", "CR-V", "Pilot", "HR-V", "Odyssey"],
  "Mazda": ["2", "3", "6", "CX-3", "CX-5", "MX-5"],
  "Subaru": ["Impreza", "Legacy", "Outback", "Forester", "Crosstrek"],
  "Mitsubishi": ["Mirage", "Outlander", "Lancer", "Pajero", "Eclipse Cross"],
  "Suzuki": ["Alto", "Swift", "Vitara", "Jimny", "SX4", "Ignis"],
  "Isuzu": ["D-Max", "MU-X"],
  
  // Premium Brands
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "E-PACE", "F-PACE"],
  "Land Rover": ["Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Evoque", "Defender"],
  "Porsche": ["911", "Boxster", "Cayman", "Panamera", "Macan", "Cayenne"],
  "Lamborghini": ["Huracán", "Revuelto", "Urus"],
  "Ferrari": ["F8", "SF90", "Roma", "Portofino"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "MC20"],
  "Bentley": ["Continental", "Flying Spur", "Bentayga"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan"],
  "Aston Martin": ["DB11", "DBS", "Vantage", "DBX"],
  "Bugatti": ["Chiron", "Bolide"],
  
  // Russian/Eastern Brands
  "Lada": ["Niva", "Vesta", "Granta", "Largus", "Kalina"],
  "Gazelle": ["Gazelle"],
  
  // Chinese Brands
  "Chery": ["Tiggo", "Arrizo", "QQ"],
  "Geely": ["Emgrand", "Boyue", "Coolray"],
  "BYD": ["Qin", "Song", "Yuan", "Atto 3"],
  "Great Wall": ["Haval", "Wey", "Ora"],
  "JAC": ["S3", "S5", "S7"],
  "MG": ["MG3", "MG5", "MG6", "MG7", "MG ZS"],
  "Changan": ["Benni", "Raize"],
  "Dongfeng": ["Aeolus", "Fengon"],
  "FAW": ["Besturn"],
  "Lifan": ["Solano", "Breeze"],
  
  // American Brands
  "GM Cadillac": ["CTS", "Escalade", "SRX", "XT5"],
  "Dodge": ["Charger", "Challenger", "Durango"],
  "Jeep": ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade"],
  "Hummer": ["H2", "H3"],
  "Buick": ["LaCrosse", "Regal"],
  
  // Korean Brands
  "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
  "Ssangyong": ["Korando", "Tivoli", "Rexton"],
};

export const POPULAR_MAKES = Object.keys(CAR_MAKES_AND_MODELS).sort();

// Romanian counties (județe)
export const ROMANIAN_COUNTIES = [
  "Alba",
  "Arad",
  "Argeș",
  "Bacău",
  "Bihor",
  "Bistrița-Năsăud",
  "Botoșani",
  "Brăila",
  "Brașov",
  "București",
  "Buzău",
  "Călărași",
  "Caraș-Severin",
  "Cluj",
  "Constanța",
  "Covasna",
  "Dâmbovița",
  "Dolj",
  "Galați",
  "Giurgiu",
  "Gorj",
  "Harghita",
  "Hunedoara",
  "Ialomița",
  "Iași",
  "Ilfov",
  "Maramureș",
  "Mehedinți",
  "Mureș",
  "Neamț",
  "Olt",
  "Prahova",
  "Sălaj",
  "Satu Mare",
  "Sibiu",
  "Suceava",
  "Teleorman",
  "Timiș",
  "Tulcea",
  "Vâlcea",
  "Vaslui",
  "Vrancea",
];

// Major cities by county (județ)
export const CITIES_BY_COUNTY: Record<string, string[]> = {
  "Alba": ["Alba Iulia", "Sebeș", "Aiud", "Blaj", "Cugir"],
  "Arad": ["Arad", "Ineu", "Chișineu-Criș", "Curtici", "Lipova"],
  "Argeș": ["Pitești", "Curtea de Argeș", "Câmpulung", "Mioveni", "Costești"],
  "Bacău": ["Bacău", "Onești", "Moinești", "Comănești", "Buhuși"],
  "Bihor": ["Oradea", "Salonta", "Marghita", "Beiuș", "Aleșd"],
  "Bistrița-Năsăud": ["Bistrița", "Beclean", "Năsăud", "Sângeorz-Băi"],
  "Botoșani": ["Botoșani", "Dorohoi", "Săveni", "Flămânzi", "Darabani"],
  "Brăila": ["Brăila", "Ianca", "Făurei", "Însurăței"],
  "Brașov": ["Brașov", "Făgăraș", "Săcele", "Codlea", "Zărnești", "Predeal", "Râșnov"],
  "București": ["Sectorul 1", "Sectorul 2", "Sectorul 3", "Sectorul 4", "Sectorul 5", "Sectorul 6"],
  "Buzău": ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pogoanele", "Pătârlagele"],
  "Călărași": ["Călărași", "Oltenița", "Budești", "Fundulea", "Lehliu Gară"],
  "Caraș-Severin": ["Reșița", "Caransebeș", "Bocșa", "Moldova Nouă", "Oțelu Roșu"],
  "Cluj": ["Cluj-Napoca", "Turda", "Dej", "Gherla", "Câmpia Turzii", "Huedin"],
  "Constanța": ["Constanța", "Mangalia", "Medgidia", "Năvodari", "Cernavodă", "Eforie Nord", "Eforie Sud", "Techirghiol"],
  "Covasna": ["Sfântu Gheorghe", "Târgu Secuiesc", "Covasna", "Întorsura Buzăului", "Baraolt"],
  "Dâmbovița": ["Târgoviște", "Moreni", "Pucioasa", "Găești", "Fieni", "Titu"],
  "Dolj": ["Craiova", "Calafat", "Băilești", "Filiași", "Segarcea"],
  "Galați": ["Galați", "Tecuci", "Târgu Bujor", "Berești"],
  "Giurgiu": ["Giurgiu", "Bolintin-Vale", "Mihăilești"],
  "Gorj": ["Târgu Jiu", "Motru", "Rovinari", "Novaci", "Târgu Cărbunești", "Turceni", "Țicleni", "Bumbești-Jiu"],
  "Harghita": ["Miercurea Ciuc", "Odorheiu Secuiesc", "Toplița", "Gheorgheni", "Cristuru Secuiesc", "Bălan", "Borsec"],
  "Hunedoara": ["Deva", "Hunedoara", "Petroșani", "Vulcan", "Lupeni", "Orăștioara de Sus", "Brad", "Hațeg"],
  "Ialomița": ["Slobozia", "Fetești", "Urziceni", "Țăndărei", "Fierbinți-Târg"],
  "Iași": ["Iași", "Pașcani", "Hârlău", "Târgu Frumos"],
  "Ilfov": ["Buftea", "Voluntari", "Pantelimon", "Popești-Leordeni", "Bragadiru", "Chitila", "Otopeni", "Măgurele"],
  "Maramureș": ["Baia Mare", "Sighetu Marmației", "Borșa", "Vișeu de Sus", "Târgu Lăpuș", "Cavnic", "Șomcuta Mare", "Ulmeni", "Seini", "Săliștea de Sus", "Tăuții-Măgherăuș"],
  "Mehedinți": ["Drobeta-Turnu Severin", "Orșova", "Strehaia", "Baia de Aramă", "Vânju Mare"],
  "Mureș": ["Târgu Mureș", "Reghin", "Sighișoara", "Târnăveni", "Ludușul de Mureș"],
  "Neamț": ["Piatra Neamț", "Roman", "Târgu Neamț", "Roznov"],
  "Olt": ["Slatina", "Caracal", "Balș", "Corabia", "Drăgănești-Olt", "Scornicești", "Piatra Olt", "Potcoava"],
  "Prahova": ["Ploiești", "Câmpina", "Sinaia", "Bușteni", "Mizil", "Băicoi", "Vălenii de Munte", "Azuga", "Breaza", "Comarnic", "Urlați"],
  "Sălaj": ["Zalău", "Șimleu Silvaniei", "Jibou", "Cehu Silvaniei"],
  "Satu Mare": ["Satu Mare", "Carei", "Negrești-Oaș", "Ardud", "Livada", "Tășnad"],
  "Sibiu": ["Sibiu", "Mediaș", "Agnita", "Cisnădie", "Copșa Mică", "Dumbrăveni", "Avrig", "Tălmaciu", "Ocna Sibiului", "Miercurea Sibiului", "Saliste"],
  "Suceava": ["Suceava", "Fălticeni", "Rădăuți", "Câmpulung Moldovenesc", "Vatra Dornei", "Gura Humorului", "Siret", "Dolhasca", "Broșteni", "Cajvana", "Liteni", "Milișăuți", "Salcea", "Solca", "Vicovu de Sus"],
  "Teleorman": ["Alexandria", "Roșiorii de Vede", "Turnu Măgurele", "Zimnicea", "Videle"],
  "Timiș": ["Timișoara", "Lugoj", "Sânnicolau Mare", "Jimbolia", "Buziaș", "Făget", "Deta", "Recaș"],
  "Tulcea": ["Tulcea", "Babadag", "Măcin", "Sulina", "Isaccea"],
  "Vâlcea": ["Râmnicu Vâlcea", "Drăgășani", "Băile Olănești", "Băile Govora", "Horezu", "Călimănești", "Brezoi", "Ocnele Mari"],
  "Vaslui": ["Vaslui", "Bârlad", "Huși", "Negrești", "Murgeni"],
  "Vrancea": ["Focșani", "Adjud", "Mărășești", "Odobești", "Panciu"],
};

// Get all cities as a flat sorted array
export const ALL_CITIES = Object.values(CITIES_BY_COUNTY)
  .flat()
  .sort();
